//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab.lightbootstrapapps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlacovuOntrackHealth_DevEntities : DbContext
    {
        public PlacovuOntrackHealth_DevEntities()
            : base("name=PlacovuOntrackHealth_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<PracticeProfile> PracticeProfiles { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<ProcedureNotification> ProcedureNotifications { get; set; }
        public virtual DbSet<ProcedureNotificationDetail> ProcedureNotificationDetails { get; set; }
        public virtual DbSet<ProcedureNotificationSurvey> ProcedureNotificationSurveys { get; set; }
    }
}
