//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab.lightbootstrapapps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeProfile
    {
        public long PracticeProfileId { get; set; }
        public Nullable<long> OrganizationId { get; set; }
        public string PracticeName { get; set; }
        public string Hours { get; set; }
        public string AppUserId { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zip { get; set; }
        public string EmailAddress { get; set; }
        public string WebsiteAddress { get; set; }
        public string AdminEmailAddress { get; set; }
        public string AdminPassword { get; set; }
        public string AdminName { get; set; }
        public string PracticeProfileLogoId { get; set; }
        public string OfficePhone { get; set; }
    }
}
