//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab.lightbootstrapapps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcedureNotification()
        {
            this.ProcedureNotificationDetails = new HashSet<ProcedureNotificationDetail>();
            this.ProcedureNotificationSurveys = new HashSet<ProcedureNotificationSurvey>();
        }
    
        public long NotificationId { get; set; }
        public string NotificationIdAuto { get; set; }
        public long PracticeProfileId { get; set; }
        public long ProcedureId { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationNote { get; set; }
        public Nullable<int> NotificationSendDay { get; set; }
        public Nullable<bool> IsPostNotification { get; set; }
        public Nullable<bool> IsPreNotification { get; set; }
        public Nullable<int> SurveyQuestionSetId { get; set; }
        public string NotificationHeader { get; set; }
        public int NotificationTypeId { get; set; }
        public string EmailTemplateId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string NotificationTimeLine { get; set; }
        public int NotificationArea { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual Procedure Procedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureNotificationDetail> ProcedureNotificationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureNotificationSurvey> ProcedureNotificationSurveys { get; set; }
    }
}
